### PR TITLE
issue-51/support for '/jobs/runs/submit' and '/jobs/runs/get-output'

### PR DESCRIPTION
**Pull request by jyothikomm**

### CODE REVIEW

**Comment by samshuster** [comment]
hey there thanks for your pull request!
I just updated the branch to get latest code from master which should fix travis build.

**Comment by samshuster** [comment]
Ok just some checkstyle issues remaining that are failing the build

**Comment by jyothikomm** [comment]
> Ok just some checkstyle issues remaining that are failing the build

Thanks! I will fix the checkstyle issues

**Comment by jyothikomm** [comment]
> Ok just some checkstyle issues remaining that are failing the build

Hi, the checkstyle error is fixed, can you please approve the PR

**Comment by samshuster** [comment]
thank you again for your contribution! The newest version should be available in maven central in ~2-3 hours.

**Comment by jyothikomm** [comment]
> thank you again for your contribution! The newest version should be available in maven central in ~2-3 hours.

Thanks for the quick action on my PR!

**Pull request merged**
